# Generated by Django 5.1.7 on 2025-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Confused')], default='C', max_length=1),
        ),
    ]
